Added sub-commands list-installed and locate.
joshglendenning/pac pull request #2
Opened 2020-09-17 19:33 UTC by sandeep-datta

Hi, please consider merging this pull request to add the following new sub-commands...

1. list-installed: List locally installed packages
2. locate FILE: Query the package which provides FILE

Regards,
Sandeep.

2020-10-07 19:24 UTC, isobit requested changes
Thanks for the contribution!

2020-10-07 19:24 UTC, isobit commented on bin/pac
> +  pac locate FILE				Query the package which provides FILE
Could you change `FILE` to `<file>`, so it's consistent with the other command documentation?

2020-10-08 14:19 UTC, sandeep-datta commented
Done!

2020-10-08 14:56 UTC, isobit approved these changes

2020-10-08 14:57 UTC, merged